.TH cyberd 8 2019-10-20 HeylelOS
.SH NAME
.PP
cyberd - Init process.
.SH SYNOPSIS
.PP
cyberd
.SH DESCRIPTION
.PP
cyberd is an init process meant for UNIX-like operating systems. It is neither a System V-like nor a BSD-like init system. It only supports daemons, and starts them upon configuration-load/reload. Each daemon is associated with a file in the configuration directory. On HeylelOS the default directory is /data/daemons. Only one instance of a daemon can run at any time, and through cyberctl(1), you may start stop or end it.
.SH FEATURES
.PP
cyberd was designed to be a daemon-leader as an init process. Its lack of other functionalities is only a proof of its UNIX-philosophy compliance.
.SH AUTHOR
.PP
Valentin Debon (valentin.debon@heylelos.org)
.SH SEE ALSO
.PP
cyberctl(1), cyberd(5).
