.\" manpage for the cyberctl init control command
.TH "cyberctl" 1 "Mon Mar 4 2019" "cyberctl"
.SH NAME
cyberctl - send command to a cyberd init instance
.SH SYNOPSIS
\fBcyberctl\fR [-t \fIwhen\fR] <\fIstart\fR|\fIstop\fR|\fIreload\fR|\fIend\fR> daemon...
.RS 0
\fBcyberctl\fR [-t \fIwhen\fR] <\fIpoweroff\fR|\fIhalt\fR|\fIreboot\fR|\fIsuspend\fR>
.RS 0
\fBcyberctl\fR \fIcctl\fR <\fIname\fR> [start|stop|reload|end|poweroff|halt|reboot|suspend]...
.SH DESCRIPTION
This command line interface is meant to execute commands to a cyberd instance.
You can start, stop, reload or force-end a daemon.
Depending on supported features, you can also poweroff, halt, reboot or suspend your system.
Finally you can create a new socket to communicate witch cyberd, and remove supported commands
for this new socket.
This allows creations of less-priviliged sockets to restrict access only to needed features of cyberd.
.SH OPTIONS
.IP "-t \fIwhen\fR"
The \fIwhen\fR specifies the unix timestamp at which the command may be executed.

.SH SEE ALSO
cyberd(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Valentin Debon (valentin.debon@heylelos.org)
