#ifndef COMMANDS_H
#define COMMANDS_H

#define COMMAND_UNDEFINED         0
#define COMMAND_CREATE_CONTROLLER 1

#define COMMAND_DAEMON_START      8
#define COMMAND_DAEMON_STOP       9
#define COMMAND_DAEMON_RELOAD     10
#define COMMAND_DAEMON_END        11

#define COMMAND_SYSTEM_HALT       16
#define COMMAND_SYSTEM_REBOOT     17
#define COMMAND_SYSTEM_SLEEP      18

#define COMMAND_IS_DAEMON(c) ((c) >= COMMAND_DAEMON_START && (c) <= COMMAND_DAEMON_END)
#define COMMAND_IS_SYSTEM(c) ((c) >= COMMAND_SYSTEM_HALT && (c) <= COMMAND_SYSTEM_SLEEP)
#define COMMAND_IS_VALID(c) ((c) == COMMAND_CREATE_CONTROLLER\
							|| COMMAND_IS_DAEMON(c)\
							|| COMMAND_IS_SYSTEM(c))

/* COMMANDS_H */
#endif
