#ifndef COMMANDS_H
#define COMMANDS_H

#define COMMAND_UNDEFINED      0
#define COMMAND_CREATE_CONTROL 1

#define COMMAND_DAEMON_START   8
#define COMMAND_DAEMON_STOP    9
#define COMMAND_DAEMON_RELOAD  10
#define COMMAND_DAEMON_END     11

#define COMMAND_SYSTEM_HALT    16
#define COMMAND_SYSTEM_REBOOT  17
#define COMMAND_SYSTEM_SLEEP   18

/* COMMANDS_H */
#endif
